#!/usr/bin/env groovy

@Library('jenkins-pipelayer')_

pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '100'))
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    stages {
        stage('Generate Jobs') {
            steps {
                checkout scm
                // this will generate jobs from folder jobs to jenkins folder pipelines
                generateJobs {
                    // the path were to look for property files
                    path = 'jobs/**/*.groovy'
                    // a link to your git repository
                    gitRemoteUrl = 'https://a-link-to-your-repository'
                    // the name of the branch your jobs are on.
                    gitConfigJenkinsBranch = 'master'
                    // a folder on jenkins to put your jobs in. (it will be created)
                    destination = 'pipelines'
                }
            }
        }
    }
}
