#!/usr/bin/env groovy

@Library('corydoras-lib')_

pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '100'))
        timeout(time: 30, unit: 'MINUTES')
    }
    stages {
        stage('Generate Jobs') {
            steps {
                lock(resource: "${env.JOB_NAME}/10", inversePrecedence: true) {
                    milestone 10
                    script {
                        commit = checkout scm
                    }
                    // this will generate jobs from folder jobs to jenkins folder pipelines
                    generateJobs 'jobs/**/*.groovy', 'pipelines', commit
                }
            }
        }
    }
}
