#!/usr/bin/env groovy

@Library('corydoras-lib')_

pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '100'))
        timeout(time: 30, unit: 'MINUTES')
    }
    stages {
        stage('Generate Jobs') {
            steps {
                lock(resource: "${env.JOB_NAME}/10", inversePrecedence: true) {
                    milestone 10
                    script {
                        commit = checkout scm
                    }
                    // Look into every subfolder of a repository to find Jenkinsfile and generate multibranch pipeline
                    generateMultiPipeline commit
                }
            }
        }
    }
}
