#!/usr/bin/env groovy

@Library('jenkins-pipelayer')_

pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '100'))
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    stages {
        stage('Generate Jobs') {
            steps {
                script {
                    commit = checkout scm
                }
                // Look into every subfolder of a repository to find Jenkinsfile and generate multibranch pipeline
                generateMultiPipeline commit
            }
        }
    }
}
