#!/usr/bin/env groovy

@Library('jenkins-pipelayer')_

pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '100'))
        timeout(time: 30, unit: 'MINUTES')
    }
    stages {
        stage('Generate Jobs') {
            steps {
                // here we used Lockable Resources plugin instead of disableConcurrentBuilds() for demo purpose 
                lock(resource: "${env.JOB_NAME}/10", inversePrecedence: true) {
                    checkout scm
                    milestone 10
                    // look for *.property files and generate jobs from them 
                    generateJobs {
                        // the path were to look for property files
                        path = 'config/*'
                        // a link to your git repository
                        gitRemoteUrl = 'https://a-link-to-your-repository'
                        // the name of the branch your jobs are on.
                        gitConfigJenkinsBranch = 'master'
                        // this option is mandatory, if you don't check it, the step will look not for peroperty files but for pipelines in folder specified by 'path'
                        useTemplate = true
                    }
                }
            }
        }
        // this stage will approve automatically the jobs generated
        stage('approve') {
            steps {
                // put a valid credential id here
                approveScripts 'jenkins_user', this
            }
        }
    }
}
